// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TabHub.API.Infrastructure.Persistence;

#nullable disable

namespace TabHub.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318222448_InitialPublicSchema")]
    partial class InitialPublicSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TabHub.API.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplay")
                        .HasColumnType("text")
                        .HasColumnName("actor_display");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id")
                        .HasName("p_k_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Config", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("p_k_configs");

                    b.ToTable("configs", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_managers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_managers_email");

                    b.ToTable("managers", "public");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.ManagerTenant", b =>
                {
                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("ManagerId", "TenantId")
                        .HasName("p_k_manager_tenants");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("i_x_manager_tenants_tenant_id");

                    b.ToTable("manager_tenants", "public");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("i_x_refresh_tokens_manager_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "public");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Col")
                        .HasColumnType("integer")
                        .HasColumnName("col");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<Guid>("QrToken")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_token");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tables");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasDatabaseName("i_x_tables_qr_token");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("i_x_tables_space_id");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cols")
                        .HasColumnType("integer")
                        .HasColumnName("cols");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_spaces");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.SpaceTranslation", b =>
                {
                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<string>("Language")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("SpaceId", "Language")
                        .HasName("p_k_space_translations");

                    b.ToTable("space_translations", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_staff");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("schema_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("i_x_tenants_slug");

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.WaiterZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ColEnd")
                        .HasColumnType("integer")
                        .HasColumnName("col_end");

                    b.Property<int>("ColStart")
                        .HasColumnType("integer")
                        .HasColumnName("col_start");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("RowEnd")
                        .HasColumnType("integer")
                        .HasColumnName("row_end");

                    b.Property<int>("RowStart")
                        .HasColumnType("integer")
                        .HasColumnName("row_start");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.HasKey("Id")
                        .HasName("p_k_waiter_zones");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("i_x_waiter_zones_space_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("i_x_waiter_zones_staff_id");

                    b.ToTable("waiter_zones", (string)null);
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.ManagerTenant", b =>
                {
                    b.HasOne("TabHub.API.Domain.Entities.Manager", "Manager")
                        .WithMany("ManagerTenants")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_manager_tenants_managers_manager_id");

                    b.HasOne("TabHub.API.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ManagerTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_manager_tenants_tenants_tenant_id");

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TabHub.API.Domain.Entities.Manager", "Manager")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_refresh_tokens_managers_manager_id");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.RestaurantTable", b =>
                {
                    b.HasOne("TabHub.API.Domain.Entities.Space", "Space")
                        .WithMany("Tables")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tables_spaces_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.SpaceTranslation", b =>
                {
                    b.HasOne("TabHub.API.Domain.Entities.Space", "Space")
                        .WithMany("Translations")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_space_translations_spaces_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.WaiterZone", b =>
                {
                    b.HasOne("TabHub.API.Domain.Entities.Space", "Space")
                        .WithMany("WaiterZones")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_waiter_zones_spaces_space_id");

                    b.HasOne("TabHub.API.Domain.Entities.Staff", "Staff")
                        .WithMany("WaiterZones")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_waiter_zones_staff_staff_id");

                    b.Navigation("Space");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Manager", b =>
                {
                    b.Navigation("ManagerTenants");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Space", b =>
                {
                    b.Navigation("Tables");

                    b.Navigation("Translations");

                    b.Navigation("WaiterZones");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Staff", b =>
                {
                    b.Navigation("WaiterZones");
                });

            modelBuilder.Entity("TabHub.API.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("ManagerTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
